### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by RedZebra123H** [jblanked/WebCrawler-FlipperZero#3]
When I run the app, my flipper crashes with the "furi_check failed" error. I am running Rogue Master firmware. I downloaded it from the flipper app store.

**Comment by jblanked** [comment]
Hey, happy to help! 

I have used this app on Unleashed and Official only, but let's see if we can figure out what's going on.

You get a furi_check failed when you open the app? Can you provide more details?

**Comment by RogueMaster** [comment]
My bad, fixed for next release... on my firmware we still use "view_dispatcher_enable_queue(app->view_dispatcher);" and I forgot to re-add it at one point....

**Comment by RedZebra123H** [comment]
Ok thanks for fixing it!

**Comment by RedZebra123H** [comment]
I just started using it and I realized that I can't change the link because the keyboard doesn't have an option to use special characters except the underscore on official firmware. Also, I cannot scroll through the characters to move the cursor's position.

**Comment by jblanked** [comment]
> I just started using it and I realized that I can't change the link because the keyboard doesn't have an option to use special characters except the underscore on official firmware. Also, I cannot scroll through the characters to move the cursor's position.

Well you're in luck 🔥 version 0.4 has the keyboard from UART terminal integrated, thanks to xMasterx. 0.4 is waiting to be approved in the app submissions.

Version 0.3 had a default link with the "usual" URL characters in it but I understand how inconvenient that could be for URLs with multiple forward slashes or hyphens 

As far as moving the cursor's position, I will look into it. Even the UART version I implemented in 0.4 has this flaw. It's likely a line of code that I missed. 

Thanks for your feedback!!

**Comment by jblanked** [comment]
Version 0.4 has been released officially: https://lab.flipper.net/apps/web_crawler

**Comment by RedZebra123H** [comment]
Ok thanks!
